package com.qinhailin.common.model;

import com.qinhailin.common.model.base.BaseFormSql;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FormSql extends BaseFormSql<FormSql> {
	public static final FormSql dao = new FormSql().dao();
}
