package com.qinhailin.common.model;

import com.qinhailin.common.model.base.BaseFormView;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FormView extends BaseFormView<FormView> {
	public static final FormView dao = new FormView().dao();
}
