package com.qinhailin.common.model;

import com.qinhailin.common.model.base.BaseMqttClient;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MqttClient extends BaseMqttClient<MqttClient> {
	public static final MqttClient dao = new MqttClient().dao();
}
