package com.qinhailin.common.model;

import com.qinhailin.common.model.base.BaseMqttAcl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MqttAcl extends BaseMqttAcl<MqttAcl> {
	public static final MqttAcl dao = new MqttAcl().dao();
}
