package com.qinhailin.common.model;

import com.qinhailin.common.model.base.BaseMqttUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MqttUser extends BaseMqttUser<MqttUser> {
	public static final MqttUser dao = new MqttUser().dao();
}
