package com.qinhailin.common.model;

import com.qinhailin.common.model.base.BaseMqttMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MqttMsg extends BaseMqttMsg<MqttMsg> {
	public static final MqttMsg dao = new MqttMsg().dao();
}
