package com.qinhailin.common.model;

import com.qinhailin.common.model.base.BaseMqttSub;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MqttSub extends BaseMqttSub<MqttSub> {
	public static final MqttSub dao = new MqttSub().dao();
}
