package com.qinhailin.common.model;

import com.qinhailin.common.model.base.BaseMqttRetain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MqttRetain extends BaseMqttRetain<MqttRetain> {
	public static final MqttRetain dao = new MqttRetain().dao();
}
