package com.qinhailin.common.model;

import com.qinhailin.common.model.base.BaseMqttAcked;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MqttAcked extends BaseMqttAcked<MqttAcked> {
	public static final MqttAcked dao = new MqttAcked().dao();
}
