package com.qinhailin.common.model;

import com.qinhailin.common.model.base.BaseSysTree;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysTree extends BaseSysTree<SysTree> {
	public static final SysTree dao = new SysTree().dao();
}
