package com.qinhailin.common.model;

import com.qinhailin.common.model.base.BaseWSysTree;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WSysTree extends BaseWSysTree<WSysTree> {
	public static final WSysTree dao = new WSysTree().dao();
}
