package com.qinhailin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMqttSub<M extends BaseMqttSub<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setClientid(java.lang.String clientid) {
		set("clientid", clientid);
		return (M)this;
	}
	
	public java.lang.String getClientid() {
		return getStr("clientid");
	}

	public M setTopic(java.lang.String topic) {
		set("topic", topic);
		return (M)this;
	}
	
	public java.lang.String getTopic() {
		return getStr("topic");
	}

	public M setQos(java.lang.Integer qos) {
		set("qos", qos);
		return (M)this;
	}
	
	public java.lang.Integer getQos() {
		return getInt("qos");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

}
