package com.qinhailin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMqttAcl<M extends BaseMqttAcl<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 0: deny, 1: allow
	 */
	public M setAllow(java.lang.Integer allow) {
		set("allow", allow);
		return (M)this;
	}
	
	/**
	 * 0: deny, 1: allow
	 */
	public java.lang.Integer getAllow() {
		return getInt("allow");
	}

	/**
	 * IpAddress
	 */
	public M setIpaddr(java.lang.String ipaddr) {
		set("ipaddr", ipaddr);
		return (M)this;
	}
	
	/**
	 * IpAddress
	 */
	public java.lang.String getIpaddr() {
		return getStr("ipaddr");
	}

	/**
	 * Username
	 */
	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	/**
	 * Username
	 */
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * ClientId
	 */
	public M setClientid(java.lang.String clientid) {
		set("clientid", clientid);
		return (M)this;
	}
	
	/**
	 * ClientId
	 */
	public java.lang.String getClientid() {
		return getStr("clientid");
	}

	/**
	 * 1: subscribe, 2: publish, 3: pubsub
	 */
	public M setAccess(java.lang.Integer access) {
		set("access", access);
		return (M)this;
	}
	
	/**
	 * 1: subscribe, 2: publish, 3: pubsub
	 */
	public java.lang.Integer getAccess() {
		return getInt("access");
	}

	/**
	 * Topic Filter
	 */
	public M setTopic(java.lang.String topic) {
		set("topic", topic);
		return (M)this;
	}
	
	/**
	 * Topic Filter
	 */
	public java.lang.String getTopic() {
		return getStr("topic");
	}

}
