package com.qinhailin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysOrg<M extends BaseSysOrg<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 部门编号和主键默认
	 */
	public M setOrgCode(java.lang.String orgCode) {
		set("org_code", orgCode);
		return (M)this;
	}
	
	/**
	 * 部门编号和主键默认
	 */
	public java.lang.String getOrgCode() {
		return getStr("org_code");
	}

	/**
	 * 上级部门编号
	 */
	public M setParentid(java.lang.String parentid) {
		set("parentid", parentid);
		return (M)this;
	}
	
	/**
	 * 上级部门编号
	 */
	public java.lang.String getParentid() {
		return getStr("parentid");
	}

	/**
	 * 上级部门名称
	 */
	public M setParentidName(java.lang.String parentidName) {
		set("parentid_name", parentidName);
		return (M)this;
	}
	
	/**
	 * 上级部门名称
	 */
	public java.lang.String getParentidName() {
		return getStr("parentid_name");
	}

	/**
	 * 部门名称
	 */
	public M setOrgName(java.lang.String orgName) {
		set("org_name", orgName);
		return (M)this;
	}
	
	/**
	 * 部门名称
	 */
	public java.lang.String getOrgName() {
		return getStr("org_name");
	}

	/**
	 * 部门负责人姓名
	 */
	public M setChief(java.lang.String chief) {
		set("chief", chief);
		return (M)this;
	}
	
	/**
	 * 部门负责人姓名
	 */
	public java.lang.String getChief() {
		return getStr("chief");
	}

	/**
	 * 部门负责人电话
	 */
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	/**
	 * 部门负责人电话
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 部门负责人手机号
	 */
	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	/**
	 * 部门负责人手机号
	 */
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	/**
	 * 部门负责人邮件
	 */
	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	/**
	 * 部门负责人邮件
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}

	/**
	 * 描述
	 */
	public M setDescript(java.lang.String descript) {
		set("descript", descript);
		return (M)this;
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getDescript() {
		return getStr("descript");
	}

	/**
	 * 级别
	 */
	public M setLev(java.lang.Integer lev) {
		set("lev", lev);
		return (M)this;
	}
	
	/**
	 * 级别
	 */
	public java.lang.Integer getLev() {
		return getInt("lev");
	}

	/**
	 * 是否停用
1：停用；
0：启用；
	 */
	public M setIsstop(java.lang.Integer isstop) {
		set("isstop", isstop);
		return (M)this;
	}
	
	/**
	 * 是否停用
1：停用；
0：启用；
	 */
	public java.lang.Integer getIsstop() {
		return getInt("isstop");
	}

}
