package com.qinhailin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMqttRetain<M extends BaseMqttRetain<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setTopic(java.lang.String topic) {
		set("topic", topic);
		return (M)this;
	}
	
	public java.lang.String getTopic() {
		return getStr("topic");
	}

	public M setMsgid(java.lang.String msgid) {
		set("msgid", msgid);
		return (M)this;
	}
	
	public java.lang.String getMsgid() {
		return getStr("msgid");
	}

	public M setSender(java.lang.String sender) {
		set("sender", sender);
		return (M)this;
	}
	
	public java.lang.String getSender() {
		return getStr("sender");
	}

	public M setNode(java.lang.String node) {
		set("node", node);
		return (M)this;
	}
	
	public java.lang.String getNode() {
		return getStr("node");
	}

	public M setQos(java.lang.Integer qos) {
		set("qos", qos);
		return (M)this;
	}
	
	public java.lang.Integer getQos() {
		return getInt("qos");
	}

	public M setPayload(byte[] payload) {
		set("payload", payload);
		return (M)this;
	}
	
	public byte[] getPayload() {
		return get("payload");
	}

	public M setArrived(java.util.Date arrived) {
		set("arrived", arrived);
		return (M)this;
	}
	
	public java.util.Date getArrived() {
		return get("arrived");
	}

}
