package com.qinhailin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDataDictionary<M extends BaseDataDictionary<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 字典编号
	 */
	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}
	
	/**
	 * 字典编号
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 字典名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 字典名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 备注
	 */
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 排序
	 */
	public M setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getOrderNum() {
		return getInt("order_num");
	}

}
