package com.qinhailin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMqttClient<M extends BaseMqttClient<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setClientid(java.lang.String clientid) {
		set("clientid", clientid);
		return (M)this;
	}
	
	public java.lang.String getClientid() {
		return getStr("clientid");
	}

	public M setState(java.lang.String state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.String getState() {
		return getStr("state");
	}

	public M setNode(java.lang.String node) {
		set("node", node);
		return (M)this;
	}
	
	public java.lang.String getNode() {
		return getStr("node");
	}

	public M setOnlineAt(java.util.Date onlineAt) {
		set("online_at", onlineAt);
		return (M)this;
	}
	
	public java.util.Date getOnlineAt() {
		return get("online_at");
	}

	public M setOfflineAt(java.util.Date offlineAt) {
		set("offline_at", offlineAt);
		return (M)this;
	}
	
	public java.util.Date getOfflineAt() {
		return get("offline_at");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

}
