package com.qinhailin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysTree<M extends BaseSysTree<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 上级Id
	 */
	public M setParentId(java.lang.String parentId) {
		set("parent_id", parentId);
		return (M)this;
	}
	
	/**
	 * 上级Id
	 */
	public java.lang.String getParentId() {
		return getStr("parent_id");
	}

	/**
	 * 名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 分类
	 */
	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 分类
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 排序
	 */
	public M setOrderNo(java.lang.Integer orderNo) {
		set("order_no", orderNo);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getOrderNo() {
		return getInt("order_no");
	}

}
