package com.qinhailin.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysFunction<M extends BaseSysFunction<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 功能名称
	 */
	public M setFuncName(java.lang.String funcName) {
		set("func_name", funcName);
		return (M)this;
	}
	
	/**
	 * 功能名称
	 */
	public java.lang.String getFuncName() {
		return getStr("func_name");
	}

	/**
	 * 是否启用(0:是,1:否)
	 */
	public M setIsStop(java.lang.Integer isStop) {
		set("is_stop", isStop);
		return (M)this;
	}
	
	/**
	 * 是否启用(0:是,1:否)
	 */
	public java.lang.Integer getIsStop() {
		return getInt("is_stop");
	}

	/**
	 * 功能url
	 */
	public M setLinkPage(java.lang.String linkPage) {
		set("link_page", linkPage);
		return (M)this;
	}
	
	/**
	 * 功能url
	 */
	public java.lang.String getLinkPage() {
		return getStr("link_page");
	}

	/**
	 * 上级编号
	 */
	public M setParentCode(java.lang.String parentCode) {
		set("parent_code", parentCode);
		return (M)this;
	}
	
	/**
	 * 上级编号
	 */
	public java.lang.String getParentCode() {
		return getStr("parent_code");
	}

	/**
	 * 上级名称
	 */
	public M setParentName(java.lang.String parentName) {
		set("parent_name", parentName);
		return (M)this;
	}
	
	/**
	 * 上级名称
	 */
	public java.lang.String getParentName() {
		return getStr("parent_name");
	}

	/**
	 * 功能类型(0:菜单,1:按钮)
	 */
	public M setFuncType(java.lang.Integer funcType) {
		set("func_type", funcType);
		return (M)this;
	}
	
	/**
	 * 功能类型(0:菜单,1:按钮)
	 */
	public java.lang.Integer getFuncType() {
		return getInt("func_type");
	}

	/**
	 * 图标
	 */
	public M setIcon(java.lang.String icon) {
		set("icon", icon);
		return (M)this;
	}
	
	/**
	 * 图标
	 */
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	/**
	 * 排序
	 */
	public M setOrderNo(java.lang.Integer orderNo) {
		set("order_no", orderNo);
		return (M)this;
	}
	
	/**
	 * 排序
	 */
	public java.lang.Integer getOrderNo() {
		return getInt("order_no");
	}

	/**
	 * 注释
	 */
	public M setDescript(java.lang.String descript) {
		set("descript", descript);
		return (M)this;
	}
	
	/**
	 * 注释
	 */
	public java.lang.String getDescript() {
		return getStr("descript");
	}

	/**
	 * 是否展开菜单(0:展开,1:不展开)
	 */
	public M setSpread(java.lang.Integer spread) {
		set("spread", spread);
		return (M)this;
	}
	
	/**
	 * 是否展开菜单(0:展开,1:不展开)
	 */
	public java.lang.Integer getSpread() {
		return getInt("spread");
	}

}
